<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE startingteam [
  <!ELEMENT startingteam (player*)>
  <!ELEMENT player (name, position, country, dorsal)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT position (#PCDATA)>
  <!ELEMENT country (#PCDATA)>
  <!ELEMENT dorsal (#PCDATA)>]>
<startingteam>
  <player>
    <name>GIORGI MAMARDASHVILI</name>
    <position>GOALKEEPER</position>
    <country>SPAIN</country>
    <dorsal>25</dorsal>
  </player>
  <player>
    <name>THIERRY CORREIA</name>
    <position>DEFENDER</position>
    <country>PORTUGAL</country>
    <dorsal>2</dorsal>
  </player>
  <player>
    <name>GABRIEL PAULISTA</name>
    <position>DEFENDER</position>
    <country>BRAZIL</country>
    <dorsal>5</dorsal>
  </player>
    <player>
    <name>MOUCTAR DIAKHABY</name>
    <position>DEFENDER</position>
    <country>EQUATORIAL GUINEA</country>
    <dorsal>12</dorsal>
  </player>
    <player>
    <name>JOSÉ GAYÀ</name>
    <position>DEFENDER</position>
    <country>SPAIN</country>
    <dorsal>14</dorsal>
  </player>
    <player>
    <name>HUGO GUILLAMÓN</name>
    <position>MIDFILDER</position>
    <country>SPAIN</country>
    <dorsal>6</dorsal>
  </player>
  <player>
    <name>YUNUS MUSAH</name>
    <position>MIDFILDER</position>
    <country>UNITED STATES</country>
    <dorsal>4</dorsal>
  </player>
  <player>
    <name>ANDRÉ ALMEIDA</name>
    <position>MIDFILDER</position>
    <country>PORTUGAL</country>
    <dorsal>18</dorsal>
  </player>
  <player>
    <name>HUGO DURO</name>
    <position>FORWARD</position>
    <country>SPAIN</country>
    <dorsal>19</dorsal>
  </player>
  <player>
    <name>JUSTIN KLUIVERT</name>
    <position>FORWARD</position>
    <country>NETHERLANDS</country>
    <dorsal>9</dorsal>
  </player>
  <player>
    <name>EDISON CAVANI</name>
    <position>FORWARD</position>
    <country>URUGUAY</country>
    <dorsal>7</dorsal>
  </player>
</startingteam>
